config/routes.rb
Rails.application.routes.draw do
  resources :postspecs
  # devise_for :userspecs
  resources :posts
  devise_for :users
  root "home#index"

  get "/home", to: "home#index"

  get "/admin", to: "admin#index"
  get "/posts", to: "posts#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    alias_action :create, :read, :update, :destroy, to: :crud # Pour ne pas se répéter

    can [:read], Post # Seul les actions :index, :show sont accessible publiquement

    if user.id
      can [:crud], Post, {user_id: user.id} # Il faut être le propriétaire d'un enregistrement pour l'éditeur
    end

    if user.admin?
      can :manage, :all # L'administrateur peut tout modifier
    end
   
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

include ImageUploader::Attachment.new(:image)

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123456"

  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exceptions
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ :show :edit :update :destroy ]
  # before_action :authorize_user!
  # load_and_authorize_ressource
  # GET /posts or /posts.json
  def index
    #  authorize! :manage, Post
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = curent_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.haml
#page
  %h1 Binvenue dans courtsik :)
  %div
    = link_to "Admin", admin_path()
  %p.passe
    - if user_signed_in?
      %div
        = link_to 'Se deconecter', destroy_user_session_path, method: :delete
    - else
      %div
        = link_to 'Se connecter', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%
=begin%>
 <%= javascript_include_tag "application", 'data-turbolinks-track' => true %> 
<%
=end%>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cours
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div{:style => "padding: 10px"}
      %p.notice
        = notice
      %p.alert
        = alert
      = yield
    = debug user_signed_in?
    = debug session.to_hash

app/views/posts/_form.html.haml
= form_with(model: post) do |form|
  - if post.errors.any?
  #error_explanation
    %h2
      = pluralize(post.errors.count, "error")
      prohibited this post from being saved:
    %ul
      - post.errors.full_messages.each do |message|
        %li= message
        
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :content
    = form.text_area :content
  .field
    = form.label :user_id
    = form.text_field :user_id
  .field
    = form.label :image
    = form.file_field :image
  .actions
    = form.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/erreur.html.haml
- if post.errors.any?
  #error_explanation
    %h2
      = pluralize(post.errors.count, "error")
      prohibited this post from being saved:
    %ul
      - post.errors.each do |error|
        %li= error.full_message

app/views/posts/index.html.haml
%head
  %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
#login-page
  %p#notice= notice
  %h1 Posts
  %table
    %thead
      %tr
        %th Name
        %th Content
        %th User
        %th{:colspan => "3"}
    %tbody
      - @posts.each do |post|
        %tr
          %td= post.name
          %td= post.content
          %td= post.user_id
          %td= link_to 'Show', post
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  %p#link
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Name:
\%&gt;
%p
  %strong Content:
  \%&gt;
%p
  %strong User:
  \%&gt;
| %&gt;
= link_to 'Back', posts_path